import { Mulish } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const mulish = Mulish({
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    display: 'swap',
})


export const metadata = {
    title: "I-Movies",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={mulish.className}>
        <Header/>
        {children}
        </body>
        </html>
    );
}
